### ISSUE TITLE
_ok_code=None raises a KeyError in sh>=0.12.0

### ISSUE THREAD

**Issue by jorisroovers** [amoffat/sh#343] opened 2016-12-01 23:28 UTC
sh versions ```1.12.0``` and up (I tested ```1.12.3```, ```1.12.4``` and ```1.12.5``` as well) don't handle setting ```_ok_code=None``` well.
In ```sh==1.11```, setting ```_ok_code=None``` would result in ```ok_code=[0]```. In ```sh>=1.12.0``` you get a ```KeyError```.

This is mostly a nuisance when updating existing code to ```sh>=0.12.0```.

Code to reproduce:
```bash
(.venv27) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ pip install sh==1.11
[output removed]
(.venv27) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ pip freeze | grep sh
sh==1.11
(.venv27) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sh import ls
>>> ls(_ok_code=None)
README.md
>>> exit()
(.venv27) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ pip install sh==1.12.5
[output removed]
(.venv27) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ pip freeze | grep sh
sh==1.12.5
(.venv27) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sh import ls
>>> ls(_ok_code=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vagrant/.venv27/local/lib/python2.7/site-packages/sh.py", line 1245, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/vagrant/.venv27/local/lib/python2.7/site-packages/sh.py", line 633, in __init__
    self.wait()
  File "/vagrant/.venv27/local/lib/python2.7/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/vagrant/.venv27/local/lib/python2.7/site-packages/sh.py", line 668, in handle_command_exit_code
    exc_class = get_exc_exit_code_would_raise(code, self.call_args["ok_code"])
  File "/vagrant/.venv27/local/lib/python2.7/site-packages/sh.py", line 1446, in get_exc_exit_code_would_raise
    exc = get_rc_exc(exit_code)
  File "/vagrant/.venv27/local/lib/python2.7/site-packages/sh.py", line 346, in get_rc_exc
    signame = SIGNAL_MAPPING[abs(rc)]
KeyError: 0
```

*edit: fixed version numbers*

**Comment by amoffat** [comment] 2016-12-02 23:55
the issue is fixed on the latest release, 1.12.6

**Closed by amoffat** 2016-12-02 23:55 UTC
