### ISSUE TITLE
Always 100% cpu usage using _bg=True

### ISSUE THREAD

**Issue by rw** [amoffat/sh#339] opened 2016-12-01 05:17 UTC
If I run this script using the latest code from master (703657b):

```python
import time

import sh

x = sh.sleep(60, _bg=True)
time.sleep(60)
x.wait()
```

CPU usage spikes to 100% and stays there for the duration of the command. Is there a way around this bug?

OSX 10.11.6, Pythons 2.7.12 and 3.5.2

**Comment by amoffat** [comment] 2016-12-01 06:26
shhh...mining bitcoins :moneybag:

thanks for reporting.  just pushed up `1.12.4` live with the regression fix.  should be fine now.  close the issue if it looks good

**Comment by rw** [comment] 2016-12-01 06:34
Much better! It's still eating up CPU though. About 5% CPU per waiting process, so when I run this is eats 20% CPU:

```python
import time

import sh

procs = []
for i in range(4):
    procs.append(sh.sleep(60, _bg=True))
time.sleep(60)

```

**Comment by amoffat** [comment] 2016-12-01 06:44
hm..not as high on my machine.  i just inserted a sleep into a freely-spinning background thread that has to run.  let me take a deeper look tomorrow

**Comment by rw** [comment] 2016-12-01 06:47
I'll close this issue since it's looking a lot better, but I do think someone should examine it further. Thanks!

**Comment by amoffat** [comment] 2016-12-01 08:55
made some more improvements in release 1.12.5 and got 100 processes down to ~5% cpu on my machine.

```python
import sh

procs = []                                                                                                        
for i in range(100):                                                                                              
    p = sh.sleep(30, _bg=True)                                                                                   
    procs.append(p)                                                                                                                                                                                                                  
[p.wait() for p in procs]
```

want to have one more look and confirm @rw ?

**Comment by rw** [comment] 2016-12-01 19:51
Looks a lot better, about 10-20% on my machine for those 100 processes.

Is there an evented way to do `wait`? It seems like a waste to be polling so much.

**Comment by amoffat** [comment] 2016-12-01 20:05
I know what you mean.  I was able to replace most of the internal polling with `threading.Event`s, but in some places, mostly related to timeouts, we have to remain responsive.  For example, there's a thread that runs `select.select` on the process's output pipe/tty.  That thread also needs to check if the timeout `Event.is_set()`, so we can't wait indefinitely on `select.select`...we can only select for a very short time.  The speed that that thread spins is directly tied with how fast the process will finish and clean up.  But the speed of that thread spinning contributes to the CPU

**Comment by rw** [comment] 2016-12-01 20:09
Ah okay. Is there an ergonomic way to let the user configure how much load this puts? E.g. if I'm running 100 procs that I know will take about 10 minutes to run, should I be able to increase the polling interval?

**Comment by amoffat** [comment] 2016-12-01 20:13
No, there's not.  The closest you would have to something like that would be to use `_fg=True`, which will spawn the process in such a way that there are no background threads, since the input/outputs will be directly connected (via os.dup2) to sys.stdin/out/err.  You would see much lower CPU usage there, but you will be unable to capture the output.

**Comment by amoffat** [comment] 2016-12-01 20:14
But you also won't be able to batch-launch processes with `_fg=True`, so that probably doesn't work for you.

**Comment by rw** [comment] 2016-12-01 20:37
I suggest adding a caveat about CPU usage to the documentation for `_bg=True`.

**Closed** 2016-12-01 20:37 UTC
Labels: bug
