### ISSUE TITLE
sh documentation is outdated 

### ISSUE THREAD

**Issue by mtelka** [amoffat/sh#674] opened 2023-05-12 20:20 UTC
The official `sh` documentation at https://amoffat.github.io/sh/ seems to be for version 1.14.0 (HTML page title says so), while the latest `sh` version is 2.0.3.  Please update.

There is also missing documentation for `new_group`/`_new_group`.

Thank you.

**Comment by amoffat** [comment] 2023-05-13 17:43
Duplicate of #656, closing

**Closed by amoffat** 2023-05-13 17:43 UTC

**Comment by amoffat** [comment] 2023-05-13 17:53
FWIW, if this is blocking you, https://github.com/amoffat/sh/blob/develop/MIGRATION.md describes the major differences
