### ISSUE TITLE
sh ABANDONED? Any active fork?

### ISSUE THREAD

**Issue by cgarciae** [amoffat/sh#511] opened 2020-02-26 21:37 UTC
There hasn't been new commits in 3 years but the project is great. 
Is there any active fork we can move to?

**Comment by meantheory** [comment] 2020-02-26 21:48
possible duplicate of #450 - project maintainer comments on roadmap

**Comment by amoffat** [comment] 2020-03-03 22:02
@cgarciae what critical bug or missing feature is blocking you?

**Comment by amoffat** [comment] 2020-03-03 23:23
Please see https://github.com/amoffat/sh/issues/512

**Closed** 2020-03-03 23:24 UTC
