### ISSUE TITLE
Regression in 1.12 causing interpreter to exit

### ISSUE THREAD

**Issue by schaffino** [amoffat/sh#334] opened 2016-11-28 09:38 UTC
I have some shell scripts that are duplicating output to both stdout and a file that seem to crash now with ssh 1.12 when logging is enabled.

With sh 1.11 the following example script wouldn't prematurely exit the interpreter. In 1.12 it never reaches the logger.info('sh didn't crashed python') line and instead exits immediately after the sh call with an exit code of 1.

```bash
LOGFILE="$(mktemp)"
STDOUT="$(mktemp)"

exec >  >(tee -a "${STDOUT}")
exec 2> >(tee -a "${LOGFILE}" >&2)


python -c "
from sh import echo
import sys,os,logging
from sys import stderr
logging.basicConfig(level=logging.INFO,stream=stderr)
logger = logging.getLogger(os.path.basename('sh_crashed'))

print echo('sh is printing stuff',_err=stderr)
logger.info('sh didn't crashed python')
"

echo "exit code =$?"

rm $LOGFILE $STDOUT
```

Output run as above:
INFO:sh.command:<Command u'/bin/echo sh is printing stuff'>: starting process
INFO:sh.command:<Command u'/bin/echo sh is printing stuff', pid 43241>: process started
exit code =1

Output without fd duplication:
INFO:sh.command:<Command u'/bin/echo sh is printing stuff'>: starting process
INFO:sh.command:<Command u'/bin/echo sh is printing stuff', pid 48484>: process started
INFO:sh.command:<Command u'/bin/echo sh is printing stuff', pid 48484>: process completed
sh is printing stuff
INFO:sh_crashed:sh did not crashed python
exit code =0

Output without logging enabled:
sh is printing stuff

exit code =0

**Comment by amoffat** [comment] 2016-11-29 01:04
Ok I just pushed a new version up on pip that fixes this bug.  It's version 1.12.1

Explanation below.  Please close the issue if things look good for you now

-----

After some investigation, what I've determined to be the cause is how sh is handling pipes on process termination.  Basically the issue stems from this PR  https://github.com/amoffat/sh/pull/252/files

Previously, in 1.11.0, pipes attached to a process's stdout/stderr were not closed when the process terminated.  Which caused @omribahumi's bug if not seeing the stdout.  The fix was included in 1.12.0 to close those pipes, causing them to flush the pending output to the reader end of the pipe.

Now your issue is because your logger is writing to stderr, and the process is writing to stderr, and stderr is now a pipe (created through `tee`).  So sh says "oh it's a pipe, let me close it so the reader end can get its output."  Unfortunately, the logger is still using it to write its log messages to, causing an io error.

I have rolled back the fix from 252.

**Closed** 2017-01-19 19:03 UTC
Labels: bug
