### ISSUE TITLE
Process killing (Python in the background) causes output to console that can't be suppressed

### ISSUE THREAD

**Issue by paul-hammant** [amoffat/sh#399] opened 2017-07-20 11:06 UTC
I have an integration test that spawns a Python process:

```
def process_output_1(self, line):
    pass

def test_something(self):
    p1 = sh.python("script.py", "param1", _out=self.process_output_1, _err_to_out=True, _bg=True)

    # some more setup here (unimportant)
    # the interaction here (unimportant)
    # some verification here (unimportant)

    try:
        p1.kill()
    except sh.SignalException_SIGKILL:
        pass
```

I still see the following output in the console, as the test runner exits (tearDown). Well sometimes I do. I just want to suppress all output, and I don't think py.sh has that capability :-(  Could it be added, please?

Some of the output I'm trying to suppress 

```
Exception in thread background thread for pid 20637:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/paul/.local/lib/python2.7/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/paul/.local/lib/python2.7/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/paul/.local/lib/python2.7/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/paul/.local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
SignalException_SIGKILL: 

  RAN: /usr/bin/python script.py param1

  STDOUT:

  STDERR:
```

**Comment by amoffat** [comment] 2017-07-20 15:27
Is that example code what you're using in your tests?  Is `p1` a global?  Otherwise I'm not seeing how you call `p1.kill()`

**Comment by paul-hammant** [comment] 2017-07-20 23:28
Yeah, my bad - I tried to turn copy/paste code into an example and missed some 'self' business. The code above is now fixed.

**Comment by remoteBranch** [comment] 2017-09-11 19:07
I am also hitting this issue, it seems like the issue is here-
```
def _start_daemon_thread(fn, name, exc_queue, *args):
    def wrap(*args, **kwargs):
        try:
            fn(*args, **kwargs)
        except Exception as e:
            exc_queue.put(e)
            ->raise<-
```

The calling function for this is in the python threading library and isn't going to handle this exception, thus by raising it the library generates the unhandled exception that produces the text. 

If you change raise to return, it seems to behave nicely. I do not understand what exc_queue.put(e) does, so I don't want to submit this as a "fix", but maybe it is that easy. In my own threaded libraries I do funnel exceptions in a thread to a queue much like that, and catch them in the main thread, I am guessing that is what you're doing there so this may be fine.

**Comment by larsyencken** [comment] 2017-11-12 15:44
This looks like a change in behaviour. I think it just needs to be documented.

Running the example from the Signals section of the docs:

```python
import sh
try:
    p = sh.sleep(3, _bg=True)
    p.kill()
except sh.SignalException_SIGKILL:
    print("killed")

# wait a moment, background thread exception will get printed to stderr
sh.sleep(3)
```

We find that "killed" is never printed. It appears that the correct exception is thrown, but it is thrown in the background thread, so the `try...except...` block in the foreground thread is silently ignored. This has been happening since f8c0a109e812c2ae3c52308ab52f24fda280411d

On the other hand, if we add `p.wait()` to the example, it works:

```python
import sh
try:
    p = sh.sleep(3, _bg=True)
    p.kill()
    p.wait()  # <-- crucial part
except sh.SignalException_SIGKILL:
    print("killed")

sh.sleep(3)
```

Now we get the expected behaviour. Maybe just update the example in the docs.

**Comment by larsyencken** [comment] 2017-11-12 16:11
I take it back. Trying the same example again, Python 3.6.3, `sh==1.12.14`, I seem to get the background thread exception printed to stderr no matter what I do.

If I add `p.wait()`, the exception is thrown in the foreground thread as expected, but it is also dumped to stderr at the same time.

**Comment by 4Oranges** [comment] 2018-01-21 08:51
@larsyencken @paul-hammant I experienced the same issue and found set `bg_exec=False` really help in this case.

**Comment by xfabre** [comment] 2018-01-27 22:25
@4Oranges ,thanks! The exact syntax is `_bg_exc=False` documented [here](http://amoffat.github.io/sh/sections/special_arguments.html#bg-exc)   
But anyway, this thread saved my life as I was struggling for a while on this one, thanks a ton.

**Comment by paul-hammant** [comment] 2018-01-29 21:17
I kinda need the thing running in the background though.  One python process running integration tests for another python process. Tests are "does the python app do the right batch operation to files in a directory"  Create, change, delete (of-files) workflow.

**Comment by xfabre** [comment] 2018-01-29 21:34
@paul-hammant Not sure I get your point here. 
Despite the flag name, I'm positive that things are running in the background: in my case a `kubectl port-forward` i.e a tunnel is launched with:

```
        process = sh.kubectl('port-forward', '--namespace', namespace, pod_name, '%d:%d' % (source_port, dest_port),
                             _out=lambda line: Common.signal_output(line, done),
                             _err=lambda line: print(line.strip('\n')),
                             _bg=True,
                             _env=new_env,
                             _bg_exc=False)
```
and then in foreground, I run commands that actually use that tunnel.
At some point the tunnel is no more needed and 
```
            try:
                process.terminate()
                process.wait()
            except sh.SignalException_SIGTERM:
                log.info("port-forward terminated.")
```
terminate it nicely with the log message.
Does it make sense?

**Comment by paul-hammant** [comment] 2018-01-30 22:20
I will give it a go and report back :)

**Comment by shark-horse** [comment] 2019-03-08 20:57
@xfabre I'm not @paul-hammant, but a solution like yours works for me!

To be picky, I don't think `process.terminate()` should be in the `try` block--it's `wait` that will throw the exception. Correct me if I'm wrong.

It's tempting to remove `wait()` and with it the `try/except`, but per the linked `_bg_exc` documentation advises it in case any other exception is thrown so we don't swallow it.

It would be nice to have a more obvious way to say "SIGTERM on this new process is fine."

I looked briefly at passing `Control+C` to the background process so it would exit with status code `0`, but gave up--that looks harder.

**Comment by larry-xmos** [comment] 2020-03-21 13:42
Confirmed that adding `_bg_exc=False` appears to get rid of the uncatchable background signal exception

For example:

```
p = sh.dd(_bg=True, _bg_exc=False) # uncatchable SIGTERM without the _bg_exc
p.terminate()
try:
    p.wait()
except sh.SignalException_SIGTERM:
    pass
```

**Comment by amoffat** [comment] 2020-04-26 21:49
Closing as this seems to be resolved.

**Closed by amoffat** 2020-04-26 21:49 UTC
