### ISSUE TITLE
Bug on OS X 10.8.4?

### ISSUE THREAD

**Issue by nox1203** [amoffat/sh#263] opened 2015-06-15 21:13 UTC
A little background information:
- I am trying to compile a kivy application for IOS on OS X.
- this is done with a python program that uses the sh package.
- i managed to make a simple test program that fails:

import sys
import os

curdir = os.path.dirname(**file**)
sys.path.insert(0, os.path.join(curdir, "tools", "external"))

import sh

test = sh.xcrun("--sdk", "iphoneos", "--show-sdk-path").strip()
print(test)

Description of a problem:
- when i run the program for the first time after machine boot
  the program is waiting with no output.
- i kill the program
- i can now run the program and it outputs the path of sdk every time

I changed the sh.py program a little so that it writes the debug messages to a file.
Debug files attached. I renamed them to png but are text files.
The test-fail is first run. I think that streamreader gets the data on kill but i may be wrong.
The test-ok is second run. This one works.

![test-fail](https://cloud.githubusercontent.com/assets/12901756/8170767/5759d918-13b3-11e5-8c67-ca5347162e32.png)
![test-ok](https://cloud.githubusercontent.com/assets/12901756/8170771/658f4eb4-13b3-11e5-8054-6ddbeb3e6469.png)

**Comment by amoffat** [comment] 2015-06-15 23:16
Here's what I would try:

Try to reproduce the problem with subprocess:
```python
import subprocess
p = subprocess.Popen(["./tools/external/xcrun", "--sdk", "iphoneos", "--show-sdk-path"], shell=False, stdout=subprocess.PIPE)
print(p.stdout)
```
(^ From memory, might need tweaking)

That will tell you if the problem is sh or xcrun.  If it's sh, i would say launch your minimal python script with [dtruss](https://opensourcehacker.com/2011/12/02/osx-strace-equivalent-dtruss-seeing-inside-applications-what-they-do-and-why-they-hang/) and make a gist of the output.

**Comment by nox1203** [comment] 2015-06-16 14:08
Thank you for your answer.

I tried with the following program:

import subprocess

p = subprocess.Popen(["xcrun", "--sdk", "iphoneos", "--show-sdk-path"], shell=False, stdout=subprocess.PIPE)
print(p.stdout.read())

and it works every time so i think it is something in sh?

I tried to trace this program with dtruss so that i have a positive sample first.
my trace command is:
sudo dtruss python mtrace.py 2> dt.log

but there is no output and in dt.log there is nothing that i can see about xcrun.

Any help on how do i run dtruss?

**Comment by amoffat** [comment] 2015-06-16 15:28
Hm..I think you'll need `-f`to follow child processes so you can see what xcrun is doing.  I don't know why there is no other output though.  I'm not too familiar with dtruss though (I have no apple machines)

The only thing that is coming to mind regarding this problem and timing issues are these lines:  https://github.com/amoffat/sh/blob/master/sh.py#L1230-L1235  I wonder if you bumped up the sleep value, if that would have any effect on the problem.

**Comment by nox1203** [comment] 2015-06-16 22:09
dtruss is not working. -f option does not change anything.
I bumped the sleep value to 0.5 but id did not change anything.

I timed the pure xcrun from command line. The results:
first run: 1.4s
second run: 0.02s 
I am sure this have something to do with a failure on first run.

Will try to change the sleep value to 5 tomorrow?
Any other suggestions?

**Comment by amoffat** [comment] 2015-06-16 22:35
I've got nothing else right now.  I'll try to find a mac machine I can test this on.  Getting dtruss to output something would help out a lot.  Try it on a normal command `sudo dtruss ls 2> dt.log` and see if you can get anything to work.

**Comment by nox1203** [comment] 2015-06-17 05:50
Sorry if i was not clear enugh about dtruss.
It works on ls.
It also works on pythom mtest.py but only shows system calls
for loading python but stops there. No trace of runing .py part.
I have a few ideas will update you if i find something.

**Comment by nox1203** [comment] 2015-06-17 21:12
Update:

1. attached dtruss to already running locked program, got the two lines repeating:
select(0xA, 0x10CFD6190, 0x10CFD6110, 0x10CFD6090, 0x10CFD6080)		 = 0 0
write_nocancel(0x4, "DEBUG:sh.command.process:<Command '/usr/bin/xcrun --sdk iphonesimulator --show-sdk-pa...(2 more)' call_args {'bg': False, 'timeout': 0, 'internal_bufsize': 31...(446 more)>.<Process 600 ['/usr/bin/xcrun', '--sdk', 'iphonesimulator', '--show-sdk-path']>: XX", 0x132)		 = 306 0
I do not think this will help?

2. tried to replicate the timing problem with two python programs
First program:
import sys
import os

curdir = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(curdir, "tools", "external"))

import sh

test = sh.python("delay.py")
print(test)

In delay.py is just a time.sleep and one print statement.
But this one works without a problem even for very long delays.

**Comment by amoffat** [comment] 2015-06-17 21:55
I managed to get on an apple machine.  I can't reproduce the problem.  I added a `--no-cache` option to xcrun to prevent it from running quickly, but It never hangs for me.  I'm using OSX 10.10.3.  I should've asked this sooner, but what version of python are you on?  I tried both 2.7 and 3.4, both using sh 1.11.

**Comment by nox1203** [comment] 2015-06-18 14:23
test script:
import subprocess

p = subprocess.Popen(["xcrun", "--sdk", "iphoneos", "--show-sdk-path"], shell=False, stdout=subprocess.PIPE)
print(p.stdout.read())

I have:
sh 1.11
python 2.7.2 - my test script not working
python 3.4  - my test script working

I tried python 3.4 first time today because the toolchain.py script for compiling kivy is for python 2.
I tried to run the toolchain.py script with python3 and get the:

sh.ErrorReturnCode_255 as last line of traceback. 

RAN: /usr/bin/xcrun --sdk iphonesimulator --show-sdk-path

STDOUT and STDERR are empty.

**Comment by amoffat** [comment] 2015-06-18 15:47
I'm a little confused.  This test script:

```python
import subprocess

p = subprocess.Popen(["xcrun", "--sdk", "iphoneos", "--show-sdk-path"], shell=False, stdout=subprocess.PIPE)
print(p.stdout.read())
```

Is not working on python2.7, but working on python3.4?   But the sh version doesn't work on python3.4 because its raising an exit code 255?

The error code 255 is a clue, but debugging it is extremely difficult, because the problem exists sometime between the child process forking, and the exec: https://github.com/amoffat/sh/blob/master/sh.py#L1298-L1302  I wouldn't be able to help unless I can reproduce it, and I can't reproduce it unfortunately.  The debugging trick would involve writing to a file the current exception traceback from within the `finally:` block.  That would tell you the line that the exception is occurring on.  It would be any one of these lines https://github.com/amoffat/sh/blob/master/sh.py#L1224-L1287, which are mostly system calls dealing with file descriptors.

It honestly sounds like there is something non-standard about your OS or python environment.  I can leave this issue open to see if anybody else has a similar problem in the future, but my help is limited unless you can make more progress on debugging it.

**Comment by nox1203** [comment] 2015-06-18 20:39
Sorry for confusion.
I meant this script.
```python
import sys
import os

curdir = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(curdir, "tools", "external"))

import sh

test = sh.xcrun("--sdk", "iphoneos", "--show-sdk-path").strip()
print(test)
```
And the results are:
python 2.7.2 - not working
python 3.4.3 - not working - same thing as with 2.7.2 - lock on first run,  works on second run.

**Comment by amoffat** [comment] 2020-04-26 23:04
Closing due to no further confirmation from other users.  Fortunately there's been fixes in the next release that will help debug the exception 255 error code if this problem occurs for anyone else.

**Closed by amoffat** 2020-04-26 23:04 UTC
