### ISSUE TITLE
sh.grep + sh.openssl not working =(

### ISSUE THREAD

**Issue by arpsyapathy** [amoffat/sh#632] opened 2022-12-02 15:34 UTC
Hi!

Help me please. I try grep in openssl result and get error
```
import sh
print(sh.grep(sh.openssl('s_client','-showcerts','-connect','mysite.com:443'), 'Ciphers'))
```
error:
```
sh.ErrorReturnCode_1:
  RAN: /bin/grep Ciphers
  STDOUT:
  STDERR:
```

if i run sh.openssl('s_client','-showcerts','-connect','mysite.com:443') i get result, but i need grep for this.

What i doing wrong?

Thank you in advanced

**Comment by ecederstrand** [comment] 2022-12-02 18:00
This is a duplicate of #629

**Closed** 2022-12-02 18:01 UTC
